### ISSUE TITLE
[Bug] Orders model incremental logic does not capture updated orders

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_shopify_holistic_reporting#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

in https://github.com/fivetran/dbt_shopify_holistic_reporting/blob/main/models/shopify_holistic_reporting__orders_attribution.sql, we use the `created_timestamp` fields of orders to determine if the order is new enough to be included in an incremental batch.
```sql
with orders as (

    select *
    from {{ ref('shopify__orders') }}

    -- just grab new orders
    {% if is_incremental() %}
        where created_timestamp >= (select max(created_timestamp) from {{ this }})
    {% endif %}
```

should be 

```with orders as (

    select *
    from {{ ref('shopify__orders') }}

    -- just grab new orders
    {% if is_incremental() %}
        where updated_timestamp >= (select max(updated_timestamp) from {{ this }})
    {% endif %}
```

i think

### Expected behavior

updated orders should be re-transformed in this model so that they are up-to-date and not being lost along the way from `shopify__orders`

### dbt Project configurations

-

### Package versions

-

### What database are you using dbt with?

bigquery

### dbt Version

-

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as PR #9 addressed this bug.
